### ISSUE TITLE
Getting Config not found issue when getting IOST using docker 

### ISSUE THREAD

**Issue by mayank-daga** [iost-official/explorer#25]
I am getting following error while setting up IOST Node using docker:

Fatal 2024-07-29 07:28:52.360 config.go:166 Failed to open config file '/var/lib/iserver/iserver.yml', open /var/lib/iserver/iserver.yml: no such file or directory
2024-07-29 12:58:52 goroutine 1 [running]:
2024-07-29 12:58:52 runtime/debug.Stack()
2024-07-29 12:58:52     /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/runtime/debug/stack.go:24 +0x5e
2024-07-29 12:58:52 github.com/iost-official/go-iost/v3/ilog.(*Logger).Fatalf(0xc000273880, {0x13adac2?, 0x0?}, {0xc00026fdb0?, 0x2?, 0xc00026fe20?})
2024-07-29 12:58:52     /go-iost/ilog/logger.go:226 +0x55
2024-07-29 12:58:52 github.com/iost-official/go-iost/v3/ilog.Fatalf(...)
2024-07-29 12:58:52     /go-iost/ilog/ilog.go:142
2024-07-29 12:58:52 github.com/iost-official/go-iost/v3/common.LoadYamlAsViper({0x7ffcc7fc4f59, 0x1c})
2024-07-29 12:58:52     /go-iost/common/config.go:166 +0x10c
2024-07-29 12:58:52 github.com/iost-official/go-iost/v3/common.NewConfig({0x7ffcc7fc4f59?, 0xc000138010?})
2024-07-29 12:58:52     /go-iost/common/config.go:178 +0x1c
2024-07-29 12:58:52 main.main()
2024-07-29 12:58:52     /go-iost/cmd/iserver/main.go:71 +0x105

**Comment by mayank-daga** [comment]
This is resolved it was volumne mapping issue
